# version: '3.8'
# services:
#   web:
#     build: .
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/app
#     depends_on:
#       - db
#   db:
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_DATABASE: 'prakt'
#       MYSQL_USER: 'root'
#       MYSQL_PASSWORD: 'FrotLig13'
#       MYSQL_ROOT_PASSWORD: 'FrotLig13'


version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'prakt'
      MYSQL_ROOT_PASSWORD: 'FrotLig13'

