version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: prakt
      MYSQL_ROOT_PASSWORD: your_root_password
    volumes:
      - ./mysql-data:/var/lib/mysql
